name: Rapportera felaktigt borttaget innehåll eller ett problem
description: Använd denna mallen för att rapportera felaktigt borttaget innehåll eller ett problem.
body:
  - type: checkboxes
    attributes:
      label: Förutsättningar
      description: För att utesluta ogiltiga problem, bekräfta och markera var och en av kryssrutorna.
      options:
        - label: Jag gjorde en [översiktlig sökning av problemspåraren](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) för att undvika att öppna en dubblett.
          required: true
        - label: Jag försökte återskapa problemet när uBlock Origin är det enda aktiverade webbläsartillägget.
          required: false
        - label: Jag försökte återskapa problemet när uBlock Origin använder standardlistor och inställningar.
          required: false

  - type: checkboxes
    attributes:
      label: Det felaktigt borttagna innehållet gör **INTE** något av följande... (Lämna tomt om du inte vet.)
      options:
        - label: Visar annonser.
          required: false
        - label: Spårar användaren på något sätt. (Detta inkluderar även anonym spårning.)
          required: false
        - label: Avbryter eller irriterar användaren. (Modala popups till exempel.)
          required: false

  - type: textarea
    attributes:
      label: Beskrivning
      description: Ge en tydlig beskrivning av problemet.
    validations:
      required: true

  - type: textarea
    attributes:
      label: URL(er) där problemet uppstår.
      description: |
        Minst en webbadress till en webbsida där problemet uppstår är **obligatoriskt**.
        Baklängescitationstecknen (`) kring länkarna är viktiga, det förhindrar att länken går att klicka på. Varna med **NSFW** när innehållet på sidan är olämpligt för arbetsplatser.
      placeholder: |
        `https://example.com`
        `https://example.org`
        `https://example.net`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Skärmdump(ar)
      description: |
        Skärmdump(ar) är bra att ha om du har svårt att beskriva problemet.
        Använd **LÄNKAR** istället för inline-bilder om skärmdumpen innehåller **VUXET INNEHÅLL**.
    validations:
      required: false

  - type: input
    attributes:
      label: Annonsblockerare och version
    validations:
      required: true

  - type: input
    attributes:
      label: Webbläsare och version
    validations:
      required: true
