name: Report unblocked ads, tracking, or annoyances
description: Use this template to report unblocked ads, tracking, or annoyances
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) to avoid opening a duplicate issue.
          required: true
        - label: I use no other ad blockers or privacy blocking tools/extensions other than my preferred one. (To rule out invalid issues it's important to use only one blocker.)
          required: true
        - label: I've tried to reproduce the issue with uBlock Origin as the only browser extension activated.
          required: false
        - label: I've tried to reproduce the issue with uBlock Origin's default settings.
          required: false

  - type: textarea
    attributes:
      label: Description
      description: Provide a clear and concise description of this issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: URL(s) where the issue occurs.
      description: |
        At least one URL to a web page where the unblocked content is located is **mandatory**.
        The backticks (`) surrounding the URL(s) are important, it prevents the URL(s) from being clickable. Warn with **"NSFW"** where applicable.
      placeholder: |
        `https://example.com`
        `https://example.org`
        `https://example.net`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) are good to have for hard-to-describe visual issues.
        Post **LINKS** instead of inline images for screenshots containing **NSFW/ADULT MATERIAL**.
    validations:
      required: false

  - type: input
    attributes:
      label: Adblocker used and version
    validations:
      required: true

  - type: input
    attributes:
      label: Browser name and version
    validations:
      required: true

  - type: textarea
    attributes:
      label: Configuration
      description: |
        On the affected site: ðŸ›¡ï¸ uBO's icon > ðŸ’¬ Report > Click "Troubleshooting information" > Select all > Copy > Paste it below.
      value: |
        <details>
        <summary>Details</summary>

        <!-- â¬‡ï¸ Paste the troubleshooting information here â¬‡ï¸ -->
        ```yaml


        ```
        </details>    
    validations:
      required: false
