# A script that looks up each domain from the file generated by domains.sh

import socket

def check_domain(domain):
  try:
      socket.gethostbyname(domain)
      return True
  except socket.gaierror:
      return False

with open('domains.txt', 'r') as file:
   domains = file.read().splitlines()

for domain in domains:
   # Ignore empty lines and lines starting with `~`
   if domain.startswith('~') or domain.strip() == '':
       continue
   if not check_domain(domain):
       print(f'{domain} is probably inactive.')
